### ISSUE TITLE
Unable to get the power_spectrum.csv

### ISSUE THREAD

**Issue by suavelad** [stiwarih/hssyp#1]
I am trying to work on your ML project for seizure detection. 
I am using Bend_Kumar_Smadja_Tiwari_CS109A_Detecting_Seizures.ipynb file and I am finding it difficult get your power_spectrum.csv .

**Comment by hannaka14** [comment]
Same issue here. I am finding it difficult to get your power_spectrum.csv. kindly share the csv file

**Comment by stiwarih** [comment]
Try opening those data files the are located here: https://github.com/stiwarih/hssyp/tree/master/project
such as https://github.com/stiwarih/hssyp/blob/master/project/CSV_FILES_1.zip

Let me know if you run into issues.

**Comment by AlineAli** [comment]
Same issue here. I could not  to find your power_spectrum.csv. kindly share the csv file

**Comment by satkuma** [comment]
[](url
[power_spectrum.csv](https://github.com/stiwarih/hssyp/files/8795287/power_spectrum.csv)
)
Hope this helps.
