### ISSUE TITLE
power_spectrum

### ISSUE THREAD

**Issue by hadinajjar** [stiwarih/hssyp#2]
Can you please provide the power_spectrum.csv file used in the scatter plot
Or tell us exactly what it contains or how it's generated and thank you

**Comment by stiwarih** [comment]
Try opening those data files the are located here: https://github.com/stiwarih/hssyp/tree/master/project
such as https://github.com/stiwarih/hssyp/blob/master/project/CSV_FILES_1.zip

Let me know if you run into issues.

**Comment by hadinajjar** [comment]
The problem in the CSV_FILES_1.zip and CSV_FILES_2.zip there are multiple csv files but none of them is named power_spectrum.csv as you are using it in your code to plot the scatter plot
