### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by hadinajjar** [stiwarih/hssyp#3]
The exact problem when trying to run your code is that you use a csv file named power_spectrum.csv the link u mentioned has multiple csv files none of them is named power_spectrum.csv 
and thanks in advance

**Comment by stiwarih** [comment]
Sorry it has been a while I suppose you may find some of those here: https://github.com/stiwarih/hssy/tree/master/Mile-6, including  power_spectrum.csv

**Comment by hadinajjar** [comment]
[https://github.com/stiwarih/hssy/tree/master/Mile-6/power_spectrum.csv](url)
the above link is not valid can you please fix it thanks in advance
